# Generated by Django 4.1.7 on 2023-02-24 16:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
