# Generated by Django 4.1.7 on 2023-02-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
