# Generated by Django 4.1.7 on 2023-02-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gameimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameimage',
            old_name='image',
            new_name='images',
        ),
    ]
